name: Build Pyodide Dependency Bundle

on:
  workflow_dispatch:

jobs:
  build-bundle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies into temp site-packages
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install git+https://github.com/FurretGoWalcc/s2protocol
        pip install git+https://github.com/Talv/sc2-repdump
        mkdir -p bundle
        rsync -av \
        --exclude='__pycache__/' \
        --exclude='*.dist-info/' \
        --exclude='*.pyc' \
        venv/lib/python*/site-packages/ dep/


    - name: Create bundle.zip
      run: |
        zip -m bundle.zip dep

    - name: Upload bundle.zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pyodide-dep-bundle
        path: bundle.zip
